<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>0e476baa-5b71-4d19-86be-07dd2153240e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shop.ApiService\Shop.ApiService.csproj" />
    <ProjectReference Include="..\Shop.Web\Shop.Web.csproj" />
  </ItemGroup>

</Project>
